name: all-in-one
on: 
  watch:
  issues:
    types: [labeled]
jobs:
  echo-all1:
    name: echo-all2
    runs-on: ubuntu-latest
    steps:
      - name: echo-all3
        run: |
          echo "${{toJson(github)}}"
  starred:
    if: github.event_name == 'watch'
    name: starred
    runs-on: ubuntu-latest
    steps:
      - name: starred
        run: |
          echo "you starred me"
  labeled:
    if: github.event_name == 'issues' && github.event.label.name == 'good first issue' || github.event.label.name == 'first-timers-only' 
    name: labeled
    runs-on: ubuntu-latest
    steps:
      - name: labeled
        run: |
          echo "you labeled me"
    
  
          
          
