name: random-test

on:
  push:
  issues:
    types: [labeled]

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          google-chrome -v
          google-chrome --disable-gpu --disable-software-rasterizer

